name: PR Lint

on:
  pull_request_target:
    types:
      - opened
      - edited

permissions:
  pull-requests: read

jobs:
  main:
    name: Title
    runs-on:
      - runs-on
      - runner=2cpu-linux-arm64	
      - run-id=${{ github.run_id }} 
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
